algo = (input('Digite algo:'))
print('O tipo premitivo desse valor é {}'.format(type(algo)))
print('Só tem espaços? {}'.format(algo.isspace()))
print('É um alfabético? {}'.format(algo.isalpha()))
print('É um número? {}'.format(algo.isnumeric()))
print('É um alfanumérico? {}'.format(algo.isalnum()))
print('Está em maiusculas? {}'.format(algo.isupper()))
print('Esta em minusculas? {}'.format(algo.islower()))
print('está capitalizada? {}'.format(algo.istitle()))